/********************************************************************
* /home/music/workspace/genfit/test/CometPhase1/myDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/music/workspace/genfit/test/CometPhase1/myDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablemyDict();
extern void G__cpp_setup_inheritancemyDict();
extern void G__cpp_setup_typetablemyDict();
extern void G__cpp_setup_memvarmyDict();
extern void G__cpp_setup_globalmyDict();
extern void G__cpp_setup_memfuncmyDict();
extern void G__cpp_setup_funcmyDict();
extern void G__set_cpp_environmentmyDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "StripHit.h"
#include "PointHit.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__myDictLN_TClass;
extern G__linked_taginfo G__myDictLN_TBuffer;
extern G__linked_taginfo G__myDictLN_TMemberInspector;
extern G__linked_taginfo G__myDictLN_TObject;
extern G__linked_taginfo G__myDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__myDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__myDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__myDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__myDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__myDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__myDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__myDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__myDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__myDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__myDictLN_TVector3;
extern G__linked_taginfo G__myDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__myDictLN_GFAbsRecoHit;
extern G__linked_taginfo G__myDictLN_GFAbsTrackRep;
extern G__linked_taginfo G__myDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__myDictLN_GFRecoHitIfclEGFPlanarHitPolicygR;
extern G__linked_taginfo G__myDictLN_StripHit;
extern G__linked_taginfo G__myDictLN_GFRecoHitIfclEGFSpacepointHitPolicygR;
extern G__linked_taginfo G__myDictLN_PointHit;

/* STUB derived class for protected member access */
